version: "3"
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=iexcloud
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  mq:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29093,OUTSIDE://localhost:9093
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28083,OUTSIDE://0.0.0.0:8083
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28083,OUTSIDE://localhost:8083
    ports:
      - 8083:8083
      - 9093:9093
      - 28083:28083
      - 29093:29093

volumes:
  pg-data:
